name: Activity Sync

on:
  schedule:
    - cron: '0 3,8,13,17,22 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Update Heartbeat
        env:
          TZ: Asia/Jakarta
        run: |
          cat <<EOF > HEARTBEAT.md
          # Repository Heartbeat 💓
          
          This file is automatically updated to keep the repository active.
          
          ### Last Sync
          - Date: $(date +'%Y-%m-%d')
          - Time: $(date +'%H:%M:%S') WIB
          - Status: **Active** 🟢
          EOF
          git config --global user.name "miuubyte"
          git config --global user.email "miuudev@gmail.com"
          git add HEARTBEAT.md
          git commit -m "chore: sync heartbeat [skip ci]" || exit 0
          git push
