name: Activity Sync

on:
  schedule:
    - cron: '0 5,17 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Update Heartbeat
        env:
          TZ: Asia/Jakarta
        run: |
          echo "- Sync: $(date)" >> HEARTBEAT.md
          git config --global user.name "miuubyte"
          git config --global user.email "miuudev@gmail.com"
          git add HEARTBEAT.md
          git commit -m "chore: sync heartbeat [skip ci]" || exit 0
          git push
